name: bindgen
channels:
  - conda-forge
dependencies:
  - occt=8.0.0=novtk*
  - cmake >=3.30
  - ninja
  - cxx-compiler
  - fmt
  {% if get_env("RUNNER_OS", default="Linux") == "Windows" %}
  - tbb-devel
  {% endif %}
  {% if get_env("RUNNER_OS", default="Linux") == "Linux" %}
  - libgl-devel
  {% endif %}
