name: OCP

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  generate_linux:
    uses: ./.github/workflows/generate_linux.yml
    secrets:
      ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

  generate_macos:
    uses: ./.github/workflows/generate_macos.yml
    secrets:
      ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

  generate_windows:
    uses: ./.github/workflows/generate_windows.yml
    secrets:
      ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

  Windows:
    needs: generate_windows
    uses: ./.github/workflows/build-windows.yml
    secrets:
      ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

  Linux:
    needs: generate_linux
    uses: ./.github/workflows/build-linux.yml
    secrets:
      ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

  OSX:
    needs: generate_macos
    uses: ./.github/workflows/build-macos.yml
    secrets:
      ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

  Windows-14t:
    needs: generate_windows
    uses: ./.github/workflows/build-windows-14t.yml

  Linux-14t:
    needs: generate_linux
    uses: ./.github/workflows/build-linux-14t.yml

  OSX-14t:
    needs: generate_macos
    uses: ./.github/workflows/build-macos-14t.yml
